// AUTHOR : FAFALI CARYN AKU AWITTOR
// DATE : 29TH SEPTEMBER,2025
// LECTURER : MR. DANIEL ADDO
// DESCRIPTION: THIS CODE IS TO HELP ASHESI UNIVERSITY'S HEALTH CENTER PILOT A TINY SELF SERVICE INTAKE KIOSK

public class HealthKiosk {
    public static void main(String[] args) {

    }
}
